### ISSUE TITLE
Pluggable logging backends

### ISSUE THREAD

**Issue by 8bitDesigner** [Fullscreen/logplexer#7]
It would be helpful to configure multiple backends for logplexer, as in prod, we want to be able to log to standard out and Honeybadger, however in development we want to log to a `/log/development.log`.

**Comment by onetwopunch** [comment]
The ability to add global configuration has been added in [v1.0.0](https://github.com/Fullscreen/logplexer/tree/v1.0.0)

**Comment by 8bitDesigner** [comment]
Works like a charm, thanks, mate!
